#!/bin/bash

#TODO: handle symlinks in a platform-independent way
STAMP_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
BASE_DIR="$( pwd )"

if [ "$#" -eq 0 ]; then
	ant -f "$STAMP_DIR/ant/stamp.xml" -Dbasedir="$BASE_DIR"
elif [ "$#" -eq 1 ]; then
	ant -f "$STAMP_DIR/ant/stamp.xml" -Dbasedir="$BASE_DIR" "$1"
elif [ "$#" -eq 2 ]; then
	TARGET="$1"
	APP_DIR="$2"
	shift
	shift
	ant -f "$STAMP_DIR/ant/stamp.xml" -Dbasedir="$BASE_DIR" "$TARGET" -Dapp="$APP_DIR" "$@"
else
	TARGET1="$1"
	APP_DIR="$2"
	ANALYSES="$3"
	shift
	shift
	shift
	shift
	ant -f "$STAMP_DIR/ant/stamp.xml" -Dbasedir="$BASE_DIR" "$TARGET1" -Dapp="$APP_DIR" -Danalyses="$ANALYSES" $@
fi
