#! /bin/sh

set -e

# mkdir -p $SOOT_FACT_GENERATION_HOME
# echo "installing in $SOOT_FACT_GENERATION_HOME"
# cp build/soot-fact-generation.jar $SOOT_FACT_GENERATION_HOME
# cp soot-fact-generation $SOOT_FACT_GENERATION_HOME

cp build/soot-fact-generation.jar $DOOP_HOME/lib
cp LICENSE $DOOP_HOME/lib/SOOT-FACT-GENERATION-LICENSE
