
// name=syncLH-dlog

.number_type H
.number_type M
.number_type V
.number_type L



.decl VH(v:V,h:H) //V0,H0
.input VH()
.decl thisMV(m:M,v:V) //M0,V0
.input thisMV()
.decl syncLM(l:L,m:M) //L0,M0
.input syncLM()
.decl syncLV(l:L,v:V) //L0,V0
.input syncLV()

.decl syncLH(l:L,h:H) //L0,H0
.output syncLH()



syncLH(l,h) :- syncLM(l,m), thisMV(m,v), VH(v,h).
syncLH(l,h) :- syncLV(l,v), VH(v,h).

