package petablox.project.analyses.parallelizer;


/**
 * Interface responsible for producing new jobs to be sent to the workers and
 * handling the results generated by the workers.
 */
public interface JobDispatcher {
	/**
	 * Ask dispatcher for a new job
	 */
	Scenario createJob(); 
	
	/**
	 * Send job result to dispatcher
	 */
	void onJobResult(Scenario scenario); 
	
	/**
	 * Inform dispatcher of an error on scenario with scenarioID
	 */
	void onError(int scenarioID); 
	
	/**
	 * Check if the dispatcher has any more jobs remaining
	 */
	boolean isDone();
	
	/**
	 * Save dispatcher state
	 */
	void saveState();
	
	/**
	 * Query about the maximum number of workers needed by the dispatcher.
	 * If the current number of workers is greater than the returned number,
	 * the master kills the extra threads
	 */
	int maxWorkersNeeded();
}
