#! /bin/sh

set -e

cp=$LOGICBLOX_HOME/bin/JavaBlox.jar:$JSGLR

mkdir -p build/content
javac -Xlint -cp $cp -d build/content $(find src -name '*.java')

if which sdf2table; then
  sdf2table -i logicblox-testsuite.sdf -o build/content/com/logicblox/unit/parsetable.tbl
  cp build/content/com/logicblox/unit/parsetable.tbl backup
else
  echo "warning: not building parsetable, no sdf2table found. using backup."
  cp backup/parsetable.tbl build/content/com/logicblox/unit/
fi

jar cvf build/logicblox-unit.jar -C build/content .
