#! /bin/bash

rootdir="$(pwd)"
doop="$rootdir"

source $doop/doop.conf

case "$1" in
  "jre1.3") linkargs="-deps ${doopconf_jre13}/lib";;
  "jre1.4") linkargs="-deps ${doopconf_jre14}/lib";;
  "jre1.5") linkargs="-deps ${doopconf_jre15}/lib";;
  "jre1.6") linkargs="-deps ${doopconf_jre16}/lib";;
  "system") linkargs="-lsystem";;
  *)        echo "error: unknown jre version"; exit 1;;
esac

echo "$linkargs"
