#! /bin/bash

set -e

rootdir=$(pwd)

function lbunit()
{
  export PATH=$LOGICBLOX_HOME/bin:$PATH
  export LD_LIBRARY_PATH=$LOGICBLOX_HOME/bin:$LD_LIBRARY_PATH
  java -cp $LOGICBLOX_HOME/bin/JavaBlox.jar:$rootdir/lib/logicblox-unit.jar:$rootdir/lib/jsglr.jar com.logicblox.unit.Main $*
}

function timing()
{
  echo -n "... "
  /usr/bin/time -f "(elapsed: %es)" $*
}

function report()
{
  echo -e '\E[01;31m'"\033[1m$1\033[0m"
}

function prepare-database()
{
  local jre=$1
  local analysis=$2
  local jar=$3

  cd $rootdir
  ./run -cache -"$jre" $analysis $jar
}

function prepare-databases()
{
  local runtime=$1
  local compiler=$2
  local analysis=$3

  for f in jars/$compiler/tests/*.jar; do
    prepare-database $runtime $analysis $f
  done

  for f in jars/$compiler/tests/hello/*.jar; do
    prepare-database $runtime $analysis $f
  done

  for f in jars/$compiler/tests/context/*.jar; do
    prepare-database $runtime $analysis $f
  done
}

function context-insensitive-testsuites()
{
  local runtime=$1
  local compiler=$2

  cd $rootdir/results/context-insensitive/$runtime/jars/$compiler

  # generic testsuites
  lbunit $rootdir/tests/basic.testsuite
  lbunit $rootdir/tests/method-resolution.testsuite
  lbunit $rootdir/tests/reachable-generic.testsuite
  lbunit $rootdir/tests/insensitive-heap-abstraction-generic.testsuite
  lbunit $rootdir/tests/generic-unix.testsuite
  lbunit $rootdir/tests/reflection.testsuite

  # specific testsuites
  lbunit $rootdir/tests/insensitive.testsuite
  lbunit $rootdir/tests/insensitive-sun-specific.testsuite
  lbunit $rootdir/tests/insensitive-imprecision.testsuite
}

function 1-call-site-sensitive-testsuites()
{
  local runtime=$1
  local compiler=$2

  cd $rootdir/results/1-call-site-sensitive/$runtime/jars/$compiler

  # generic testsuites
  lbunit $rootdir/tests/basic.testsuite
  lbunit $rootdir/tests/method-resolution.testsuite
  lbunit $rootdir/tests/reachable-generic.testsuite
  lbunit $rootdir/tests/insensitive-heap-abstraction-generic.testsuite
  lbunit $rootdir/tests/generic-unix.testsuite
  lbunit $rootdir/tests/reflection.testsuite

  # specific testsuites
  lbunit $rootdir/tests/1-call-site-sensitive.testsuite
}

function 1-object-sensitive-testsuites()
{
  local runtime=$1
  local compiler=$2

  cd $rootdir/results/1-object-sensitive/$runtime/jars/$compiler

  # generic testsuites
  lbunit $rootdir/tests/basic.testsuite
  lbunit $rootdir/tests/method-resolution.testsuite
  lbunit $rootdir/tests/reachable-generic.testsuite
  lbunit $rootdir/tests/insensitive-heap-abstraction-generic.testsuite
  lbunit $rootdir/tests/generic-unix.testsuite
  lbunit $rootdir/tests/reflection.testsuite

  # specific testsuites
  lbunit $rootdir/tests/1-object-sensitive.testsuite
}

function 1-call-site-sensitive+heap-testsuites()
{
  local runtime=$1
  local compiler=$2

  prepare-database $runtime 1-call-site-sensitive+heap jars/$compiler/tests/context/Main.jar
  cd $rootdir/results/1-call-site-sensitive+heap/$runtime/jars/$compiler

  # generic testsuites
  # lbunit $rootdir/tests/basic.testsuite || echo "failed, but continuing ... "
  # lbunit $rootdir/tests/method-resolution.testsuite || echo "failed, but continuing ... "
  # lbunit $rootdir/tests/reachable-generic.testsuite || echo "failed, but continuing ... "

  # specific testsuites
  lbunit $rootdir/tests/1-call-site-sensitive+heap.testsuite
}

function 1-object-sensitive+heap-testsuites()
{
  local runtime=$1
  local compiler=$2

  prepare-database $runtime 1-object-sensitive+heap jars/$compiler/tests/context/Main.jar
  cd $rootdir/results/1-object-sensitive+heap/$runtime/jars/$compiler

  # generic testsuites
  # lbunit $rootdir/tests/basic.testsuite || echo "failed, but continuing ... "
  # lbunit $rootdir/tests/method-resolution.testsuite || echo "failed, but continuing ... "
  # lbunit $rootdir/tests/reachable-generic.testsuite || echo "failed, but continuing ... "

  # specific testsuites
  lbunit $rootdir/tests/1-object-sensitive+heap.testsuite
}

function basic()
{
  ./compile-tests

  # context-insensitive
  prepare-databases jre1.3 jre1.3 context-insensitive
  context-insensitive-testsuites jre1.3 jre1.3

  # 1-call-site-sensitive
  prepare-databases jre1.3 jre1.3 1-call-site-sensitive
  1-call-site-sensitive-testsuites jre1.3 jre1.3

  # 1-object-sensitive
  prepare-databases jre1.3 jre1.3 1-object-sensitive
  1-object-sensitive-testsuites jre1.3 jre1.3

  # 1-object-sensitive+heap
  1-object-sensitive+heap-testsuites jre1.3 jre1.3

  # 1-call-site-sensitive+heap
  1-call-site-sensitive+heap-testsuites jre1.3 jre1.3
}

function main()
{
  basic

  prepare-databases jre1.4 jre1.4 context-insensitive
  context-insensitive-testsuites jre1.4 jre1.4

  prepare-databases jre1.5 jre1.5 context-insensitive
  context-insensitive-testsuites jre1.5 jre1.5

  prepare-databases jre1.6 jre1.6 context-insensitive
  context-insensitive-testsuites jre1.6 jre1.6
}


function reflect()
{
  local runtime=jre1.3
  local compiler=jre1.3

  prepare-database $runtime context-insensitive jars/$compiler/tests/hello/Reflect.jar
  cd $rootdir/results/context-insensitive/$runtime/jars/$compiler
  lbunit $rootdir/tests/reflection.testsuite
}

if test "x$1" = "x"; then
  main
else
  $1
fi

