#! /bin/bash
#
# Script used to translate old-style test suites to bloxunit suites and execute them.
#
# The script will look for old-style suites at a "tests" directory in the currently executing
# path. If specified, it can process a single suite, otherwise it will process all generic
# suites.
#
# Parameters:
#   $1 - the directory used to store the translated suites, relative to the current path.
#   $2 - an optional suite name to process. If not available, all generic suites will be processed.
#
# Example: 
#    run-bloxunit-suite results/context-insensitive/jre1.3/jars/jre1.3 basic
#
#    will process the file tests/basic.testsuite, translate to the directory
#    results/context-insensitive/jre1.3/jars/jre1.3/basic and execute all suites in this directory.
#
set -e

rootdir=$(pwd)

#
# Yeah, yeah, we get the output directory here...
#
outputdir=$rootdir/$1
prefix="../../"

#
# Translates the suite in file $1 to the output directory $2, using prefix $3
#
function translate()
{
  export PATH=$LOGICBLOX_HOME/bin:$PATH
  export LD_LIBRARY_PATH=$LOGICBLOX_HOME/bin:$LD_LIBRARY_PATH
  java -cp $LOGICBLOX_HOME/bin/JavaBlox.jar:$rootdir/lib/logicblox-unit.jar:$rootdir/lib/jsglr.jar com.logicblox.unit.translator.Translator $*
}

#
# Executes bloxunit suites for all directories found in $1
#
function run-suites()
{
  for f in $1/*
  do
    run-suite $f
  done
}

#
# Executes bloxunit on the suite defined by $1
#
function run-suite()
{
    echo "Running suite $1"
    bloxunit -suite $1
}

#
# Translates the old suite named $1 and executes all new suites generated from it.
#
function translate-and-run()
{
   translate $rootdir/tests/$1.testsuite $outputdir/$1 $prefix
   cd $outputdir
   run-suites $1
}

#
# If $2 is empty, translate and run all available generic suites. Otherwise,
# translate and run only the suite named after $2.
#
function main()
{
  if test "x$2" = "x"; then
    echo "Running all generic suites."
    translate-and-run "basic"
    translate-and-run "method-resolution"
    translate-and-run "reachable-generic"
    translate-and-run "insensitive-heap-abstraction-generic"
    translate-and-run "generic-unix"
    translate-and-run "reflection"
  else
    echo "Running $2 suites."
    translate-and-run $2
  fi
}

#
# Output directory is mandatory
#
if test "x$1" = "x"; then
  echo "Usage: run-bloxunit-suite <translation-outputdir> [suite]"
else
  main $*
fi


